version: "3.7"

name: star_wars

networks:
  web:
    external: true

services:
  star_wars:
    build: .
    container_name: star_wars
    networks:
      - web
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.starwars.rule=Host(`starwars.erikna.com`)"
      - "traefik.http.routers.starwars.entrypoints=web, websecure"
      - "traefik.http.routers.starwars.tls=true"
      - "traefik.http.routers.starwars.tls.certresolver=production"
